-- attraction 테이블 생성
CREATE TABLE IF NOT EXISTS attraction (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content_id VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    addr1 VARCHAR(500),
    addr2 VARCHAR(500),
    area_code VARCHAR(10),
    sigungu_code VARCHAR(10),
    cat1 VARCHAR(50),
    cat2 VARCHAR(50),
    cat3 VARCHAR(100),
    mapx VARCHAR(50),
    mapy VARCHAR(50),
    mlevel VARCHAR(10),
    tel VARCHAR(50),
    zipcode VARCHAR(20),
    firstimage VARCHAR(500),
    firstimage2 VARCHAR(500),
    content_type_id VARCHAR(10),
    created_time VARCHAR(20),
    modified_time VARCHAR(20),
    booktour VARCHAR(10),
    INDEX idx_title (title),
    INDEX idx_area (area_code, sigungu_code),
    INDEX idx_location (mapy, mapx)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;