// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHPqW9EE1QB9zPi0AO-eylYnbCazFo00g',
    appId: '1:230969693841:web:1d07f658911b58089d9130',
    messagingSenderId: '230969693841',
    projectId: 'test-fe6b6',
    authDomain: 'test-fe6b6.firebaseapp.com',
    databaseURL:
        'https://test-fe6b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-fe6b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgaLFu8F6oeTkxS7Q4HGplsPSDfB971xM',
    appId: '1:230969693841:android:379aa3b6bb02d3c49d9130',
    messagingSenderId: '230969693841',
    projectId: 'test-fe6b6',
    databaseURL:
        'https://test-fe6b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-fe6b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2hmBAzWgdT5D8IUSjp2ulB5DTGxr9N6g',
    appId: '1:230969693841:ios:4602c5fb89ccb3389d9130',
    messagingSenderId: '230969693841',
    projectId: 'test-fe6b6',
    databaseURL:
        'https://test-fe6b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-fe6b6.firebasestorage.app',
    androidClientId:
        '230969693841-guvmcchdvinl9j5urv55hq3uv5ss3k4q.apps.googleusercontent.com',
    iosClientId:
        '230969693841-0j4i533oht2b4ol44reh35q2lonns636.apps.googleusercontent.com',
    iosBundleId: 'com.eastcompany.east',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2hmBAzWgdT5D8IUSjp2ulB5DTGxr9N6g',
    appId: '1:230969693841:ios:fd561ad7462ec6c99d9130',
    messagingSenderId: '230969693841',
    projectId: 'test-fe6b6',
    databaseURL:
        'https://test-fe6b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-fe6b6.firebasestorage.app',
    androidClientId:
        '230969693841-678bv1hjophka5bbplk8l1eponhhs9a6.apps.googleusercontent.com',
    iosClientId:
        '230969693841-6ee1f8eebrru703oc2oo0kpqu9uu8lj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHPqW9EE1QB9zPi0AO-eylYnbCazFo00g',
    appId: '1:230969693841:web:bfc82280b8710e9e9d9130',
    messagingSenderId: '230969693841',
    projectId: 'test-fe6b6',
    authDomain: 'test-fe6b6.firebaseapp.com',
    databaseURL:
        'https://test-fe6b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-fe6b6.firebasestorage.app',
  );
}
